### ISSUE TITLE
AjaxSelectWidget not working for custom vocabularies on add view

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1027]
I registered a custom vocabulary 'fhnw.vocabularies.Oes' and added it to a tuple field:
```
    form.widget('oes', SelectWidget)
    oes = schema.Tuple(
            title=_(u"Oes"),
            description=_(u"Organizational Units"),
            required=False,
            value_type=schema.TextLine(),
            missing_value=(),
        )
    directives.widget(
        'oes',
        AjaxSelectFieldWidget,
        vocabulary='fhnw.vocabularies.Oes'
    )
```
Accessing the vocabulary via Ajax works in edit mode but gives an ``` {"error": "Vocabulary lookup not allowed"} ``` on the add view.

Digging a little shows that the IFieldPermissionChecker in plone.app.content.browser.vocabulary does not work because the getVocabulary-view is bound to the portal as it is on the context in the edit mode. Any ideas how to fix this?

**Comment by thet** [comment]
One thing you can do is to add your vocabulary to the ``_permissions`` dict:
```
from plone.app.content.browser.vocabulary import _permissions
_permissions['fhnw.vocabularies.Oes'] = 'View'
```

**Comment by davisagli** [comment]
This may be related to https://github.com/plone/plone.dexterity/issues/40

**Comment by vangheem** [comment]
@alecpm did most of this work. He might have some ideas here. 

@thet suggestion would work. We need a better way to add permissions to vocabularies.

**Comment by alecpm** [comment]
This code: 

https://github.com/plone/plone.app.widgets/commit/10131d30c3ec71002a326fc729aa5f8158b2a4d9
https://github.com/plone/plone.app.widgets/commit/204d5a2573d10fce3a05d8772797ab549ad39c90

Should ensure that the getVocabulary request goes to a factory object (using request['URL']) unless the request 'URL' is missing/empty.  If the getVocabulary request is going to the portal instead, then either the request URL is somehow missing, or something has changed in the refactoring of the widget code so that that code isn't being called where it's needed.  This definitely worked previously, and I have production sites running with schema definitions similar to the above.

Where does the actual widget code live at this point?

**Comment by vangheem** [comment]
widget code is in plone.app.z3cform. Vocabulary view is in plone.app.content

**Comment by alecpm** [comment]
Thanks, I'll see if I can reproduce this later today and hopefully get to the bottom of it.

**Comment by alecpm** [comment]
This should be fixed with the latest commits to plone.app.dexterity and plone.dexterity, as should the issue @davisagli mentions above.  Let me know if it works for you.  Also, you should be able to use a choice field with a vocabulary source as the value type and not need to set the vocabulary for the widget.

**Comment by tomgross** [comment]
Hi @alecpm 
thanks for looking into this. Unfortunately the fixes in the Dexterity packages does not fix my issue. I Still get a *{"error": "Vocabulary lookup not allowed"}* in the getVocabulary AJAX call with a checkout of plone.dexterity and plone.app.dexterity.

**Comment by alecpm** [comment]
Is the getVocabulary AJAX call going to the AddForm url or to the portal root or someplace else entirely?

**Comment by tomgross** [comment]
One part of the solution is here: https://github.com/plone/plone.app.z3cform/pull/36

**Comment by tomgross** [comment]
The other is part is to remove the check either here:
https://github.com/plone/plone.app.dexterity/commit/5acbea6c3c1a599cc8376f739c19f5ae3a3597a0#diff-f97bdd3158e655558bbfd4052e5d61c4R64 or 
change the *AjaxSelectFieldWidget* to this:

```
@implementer(IFieldWidget)
def AjaxSelectFieldWidget(field, request, extra=None):
    """ An AjaxSelectWidget with a vocabulary
    """
    if extra is not None:
        request = extra
    widget = FieldWidget(field, AjaxSelectWidget(request))
    if getattr(field, 'value_type', None) and getattr(field.value_type, 'vocabularyName', None):
        widget.vocabulary = field.value_type.vocabularyName
    return widget
```

I prefer the first solution.

**Comment by shadowmint** [comment]
This appears to be an issue for the `RelationChoice` when it sits inside a `DataGridFieldFactory` as well.

When not in the data grid, the vocab request looks like this:

    http://192.168.15.156:8080/Plone/tests/@@edit-tile/tests.phase2.hero/73c3ee1ed674419ab2d53927d99a635e/++widget++tests.phase2.hero.video/@@getSource?query={%22criteria%22%3A[]%2C%22sort_on%22%3A%22is_folderish%22%2C%22sort_order%22%3A%22reverse%22}&attributes=[%22UID%22%2C%22Title%22%2C%22portal_type%22%2C%22path%22%2C%22getIcon%22]&batch={%22page%22%3A1%2C%22size%22%3A10}&_=1457925947002

    {"total": 1, "results": [{"getIcon": "image.png", "path": "/media/4qrcrmn.jpg", "portal_type": "Image", "UID": "ea5f0221f68a45109ccef67085c4e0f3", "Title": "Image1"}]}

When it does sit in a data grid (notice the base url for the request):

    http://192.168.15.156:8080/Plone/tests/@@edit-tile/tests.phase2.matrix/0650023517d0480185ed524f8647a2da/++widget++tests.phase2.matrix.tiles.AA.widgets.image/@@getSource?query={%22criteria%22%3A[]%2C%22sort_on%22%3A%22is_folderish%22%2C%22sort_order%22%3A%22reverse%22}&attributes=[%22UID%22%2C%22Title%22%2C%22portal_type%22%2C%22path%22%2C%22getIcon%22]&batch={%22page%22%3A1%2C%22size%22%3A10}&_=1457922463992

    {"error": "Vocabulary lookup not allowed."}

With a model like this:

```
class IMatrixTile(form.Schema):
    title = schema.TextLine(
        title=u'Tile title',
        required=True)
    content = schema.Text(
        title=u'Tile content',
        required=True)
    link = schema.TextLine(
        title=u'URL',
        required=True)
    image = RelationChoice(
        title=u'Tile Image',
        source=CatalogSource(portal_type=['Image']),
        required=True,
    )

class IMatrix(model.Schema):
    form.widget(tiles=DataGridFieldFactory)
    tiles = schema.List(
        title=u'List of tiles',
        value_type=DictRow(title=u'Tiles', schema=IMatrixTile))
```

**Comment by thet** [comment]
That should be fixed now. This PR introduces a fallback to the "View" permission, if for a vocabulary no other permission was defined: https://github.com/plone/plone.app.content/pull/85

@tomgross please verify.

**Comment by tomgross** [comment]
seems ok. Thanks @thet
