### ISSUE TITLE
Upgrade from 4 to 5 missing some steps

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#1306]
So far I've seen these missing packages not getting installed:
- plone.resource
- plone.app.theming
- plone.app.caching

There may be others.

\cc @tkimnguyen

**Comment by mauritsvanrees** [comment]
- plone.resource was fixed: https://github.com/plone/plone.app.upgrade/pull/88
- plone.app.theming is included in fresh pull request https://github.com/plone/plone.app.upgrade/issues/98
- plone.app.caching may not be needed. Then again, in a new Plone Site it is installed, just not enabled. And in an upgraded site, you cannot install through the Plone UI but need to go to `portal_setup`, which is not nice.

**Comment by gforcada** [comment]
So only p.a.caching is still not installed via an upgrade, should it be?

**Comment by mauritsvanrees** [comment]
Let's see:

- plone.app.caching has been included in the versions since Plone 4.1.
- I did not check 4.1, but on 4.2 and 4.3 it is not installed by default, but can be installed in the add-ons control panel. Seems fine.
- In Plone 5.0 it is installed by default. On upgrading, it is not installed, and not installable because the CMFPlone setuphandlers hide the product.

So yes, we should install it during the upgrade to Plone 5.0 alpha. I'll make a pull request.

**Comment by mauritsvanrees** [comment]
These have all been dealt with, just not yet released.
