### ISSUE TITLE
Site Setup parent links on Control Panel pages aren't consistent

### ISSUE THREAD

**Issue by davidjb** [plone/Products.CMFPlone#1478]
There's currently inconsistency in the way Control Panels display their parent Site Setup links.  Some look like one of the following:

![button style](https://cloud.githubusercontent.com/assets/1002811/13867436/97860cce-ed0a-11e5-8e69-57c1f2fa0d9e.png)
![link style](https://cloud.githubusercontent.com/assets/1002811/13867445/a5d3b83a-ed0a-11e5-9bbe-f9726ec20f07.png)
or else have no link/button at all:
![no link](https://cloud.githubusercontent.com/assets/1002811/13867454/b8271c66-ed0a-11e5-9858-8930a752713c.png)

Each control panel's template (as best as I can tell) uses the `prefs_main_template` template, but  implement their own Site Setup link, leading to this inconsistency as some include the `link-parent` class and some don't, assuming the link is present.

My initial suggestion was to move the `<a id="setup-link" ...>Site Setup</a>` into [prefs_main_template.pt](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_prefs/prefs_main_template.pt) and remove it from all other templates, but a fix for #700, putting `Site Setup` into the breadcrumbs might be a better approach.   Thoughts?

Tested with Plone 5.0.3-pending.

**Comment by djay** [comment]
if we want even better consistency we should also remove the menus, search, header footer etc. all accept some breadcrumbs. It should also, always be variable width. 
Those elements don't make a lot sense since the context of sitesetup is not really the root of the site or anything content related. There is nothing "inline" about site setup. This also makes the job of the themer easier as there is less concern over theming the site setup. I get bored of ensuring "users and groups" can still function on fixed width themes.

**Comment by davilima6** [comment]
+1 for the breadcrumbs #700 approach, until we decide which way to go (#1379): 1) overlays, 2) removing header/footer or 3) ...?

**Comment by jensens** [comment]
should be fixed by @agitator some time ago

**Comment by davilima6** [comment]
I think this needs to reopened because following panels have no breadcrumbs or Site Setup button:

- http://localhost:8080/@@actions-controlpanel
- http://localhost:8080/@@content-controlpanel
- http://localhost:8080/@@redirection-controlpanel
- http://localhost:8080/@@rules-controlpanel

The only panel that has breadcrumb is Dexterity Types (http://localhost:8080/@@dexterity-types) so it seems possible to be done for:

Panels lacking only Breadcrumbs:
- http://localhost:8080/prefs_install_products_form
- http://localhost:8080/@@discussion-controlpanel
- http://localhost:8080/@@usergroup-userprefs
- http://localhost:8080/@@dateandtime-controlpanel
- http://localhost:8080/@@language-controlpanel
- http://localhost:8080/@@mail-controlpanel
- http://localhost:8080/@@navigation-controlpanel
- http://localhost:8080/@@search-controlpanel
- http://localhost:8080/@@site-controlpanel
- http://localhost:8080/@@social-controlpanel
- http://localhost:8080/@@theming-controlpanel

Panels lacking Breadcrumbs and with broken formatting of Site Setup Button:
- http://localhost:8080/prefs_error_log_form
- http://localhost:8080/@@filter-controlpanel
- http://localhost:8080/@@maintenance-controlpanel
- http://localhost:8080/@@resourceregistry-controlpanel

**Comment by davisagli** [comment]
The situation is much improved in Plone 6. All control panels now use a consistent tabbed interface. I just see the following control panels that still have an extra site setup link that should be removed:
- /@@inspect-relations
- /@@member-fields
- /@@maintenance-controlpanel
- /@@language-controlpanel

**Comment by jensens** [comment]
Mostly fixed in Plone 6 per davisagli (Aug 2022), but 4 control panels still have an extra Site Setup link. Small cleanup task.

**Comment by jensens** [comment]
Note: #3617 (inconsistent breadcrumbs for control panels) was closed as duplicate of this issue. Both track the same remaining inconsistencies in Plone 6.
