### ISSUE TITLE
Regression: paste buttons should check for the __cp cookie

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#2296]
If I go to the `@@folder_contents` view, on Plone 5.0.8 the paste button is disable until I copy something:

![image](https://user-images.githubusercontent.com/1300763/35979164-f0c467b4-0ce7-11e8-8d1e-d6ee70a94e59.png)

On Plone 5.1rc2 the button is always enabled:

![image](https://user-images.githubusercontent.com/1300763/35979252-255e50d4-0ce8-11e8-8f09-b3e4b762370a.png)

**Comment by ale-rt** [comment]
Maybe fixed by https://github.com/plone/mockup/commit/9576b3ec833c4e978486a038c386fdf9861b24a9

**Comment by jensens** [comment]
@thet can you confirm this?

**Comment by gp54321** [comment]
@ale-rt : this fix you were considering in Februar is in Plone (at least in 5.1.2) and the problem is still here.

My guess: this [change](https://github.com/plone/mockup/commit/b470e3505b870896009a40ef9e54ce28e7af4529#diff-599bb9dd7f168ce749d908c88dfa06c1) seems a much more likely culprit.

**Comment by ale-rt** [comment]
Thanks for your findings @gp54321!

**Comment by vincentfretin** [comment]
@gp54321 @ale-rt 
In https://github.com/plone/mockup/pull/996
I reverted part of https://github.com/plone/mockup/commit/b470e3505b870896009a40ef9e54ce28e7af4529
to fix the disabled state of action buttons in folder contents that are using `<a>` tag and not `<button>` or `<input>`

@gp54321 You said in your comment https://github.com/plone/mockup/commit/b470e3505b870896009a40ef9e54ce28e7af4529#commitcomment-29331299 there was another regression in thememapper http://0.0.0.0:8080/Plone/++theme++newtheme/@@theming-controlpanel-mapper about the `Tools->Build CSS` that wasn't disabled when not selecting a less file? Reverting the commit did not bring the feature back. Maybe there was another change in plone.app.theming since then...
Which version of Plone was it when you said the revert of the commit brought back the feature?

**Comment by vincentfretin** [comment]
Ah from this screenshot https://github.com/plone/plone.app.theming/issues/86#issue-108505070 we had no Tools dropdown before, so I guess you were talking of the button Build CSS in these old version.

**Comment by vincentfretin** [comment]
The Build CSS button was changed from a ButtonView (which I fixed) to an AnchorView in this commit
https://github.com/plone/mockup/commit/3a414c24b69e0c4573591d421cb88e320a519aa0#diff-c4515929473f2d17ec9b635ce0d70e14R545
AnchorView has the same issue using `prop('disabled')` on a `<a>` tag. If I do a similar fix, the button have the disabled class, but it doesn't look like it's disabled, so maybe there is now a css issue with this Tools dropdown.

**Comment by vincentfretin** [comment]
Yep, I added a css rule to fix it. https://github.com/plone/mockup/pull/996 fixes all issues now.
