### ISSUE TITLE
Delete in folder_contents -> fragile, error-prone, attack vector

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2305]
The current implementation of the delete operation in the folder_contents view is neither user friendly nor stable, in some cases dangerous. The Plone is that Plone seems to check for the number of content items to be deleted in order to show a confirmation request. There is a big problem for large folders:

- the spinning wheel starts directly as soon as you click on the trashcan icon
- you can close the interim popup "Delete selected items....Loading...." -> spinning wheels remains
- the lookup of the items to be deleted can take for ages (around 2 minutes for 

312 Objects in all
304 Folders
296 Published objects

- the user may try to reload the page and start over with the delete operation

- each long running lookup will block a worker thread

This could be used as an attack vector for bringing down a Plone site.

I don't know why it takes 2 minutes for performing the lookup . I assume the related code is walking through all objects instead of asking the catalog?

Anyway...the behavior is fine for small amounts of content, it's a huge and dangerous problem for large amounts of content items.

**Comment by jensens** [comment]
An attack vector if one has delete permissions anyway? Come on. 

This is indeed a problem, I agree on the other points made. And the UI ones are need fixes here. 

But this problem is not new. Deleting large structures in Plone always had those problems. 
This can be solved only by splitting the delete in more than one transaction, I suppose.

**Comment by zopyx** [comment]
The problem is of course not new - as old as Zope. 
Attack vector - intentional or unintentional...you can bring a Plone site down easily or at least block it and make it unresponsive for some time.

**Comment by pgrunewald** [comment]
The speed issue should be resolved, once https://github.com/plone/plone.app.linkintegrity/issues/100 is merged.

@jensens: To split the actual deletion into multiple transactions would be also good for another reason, because then it would behave like the other operations that allow partly successes (e.g. the renaming dialog allows fails, applying workflows transitions allows fails etc.).

**Comment by jensens** [comment]
Verified still present. DeleteActionView does catalog(UID=selection) then getObject() for all items with no batching or async. Large selections block a worker thread.
