### ISSUE TITLE
Breadcrumbs messed up by long titles

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2433]
See screenshot (Plone 5.1.2.1)
![screenshot-dev zopyx de-5080-2018 05 30-08-25-59](https://user-images.githubusercontent.com/594239/40702722-30790034-63e3-11e8-9120-48e63179180b.png)

**Comment by pbauer** [comment]
This is fixed in Plone 6 (classic)
<img width="1401" alt="breadcrumbs" src="https://user-images.githubusercontent.com/453208/129152126-ba4b176c-37c0-4fcb-b1ea-82fdd01c1c63.png">

**Comment by ale-rt** [comment]
I stumbled in to this one day, I mitigated it with:
```
.plone-breadcrumb ol {
    white-space: nowrap;
}
```
I wonder what could be an acceptable solution... 
Even if Plone 6 is not affected in the same way, it still does not look good.
Maybe the text should be cropped and displayed in full when hovering (that might have some accessibility implications).

It would also be interesting to investigate what the other web frameworks do in similar cases.

**Comment by yurj** [comment]
Time for a "exclude from breadcrumbs"? Long and in the middle path titles should not be displayed in breadcrumb.

**Comment by ale-rt** [comment]
> Time for a "exclude from breadcrumbs"? Long and in the middle path titles should not be displayed in breadcrumb.

That might be a good idea for a new issue...

**Comment by davisagli** [comment]
Closing since the original issue here was fixed.
