### ISSUE TITLE
Templates should use @@images.tag

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3535]
Several templates use code like this:

```
<img tal:define="scale context/@@images"
    tal:replace="structure python:scale.scale('image', scale='large').tag(css_class='figure-img img-fluid')" />
```

Instead of first calling the `scale` function and calling `tag` on the result, we should call the `tag` method directly:

```
<img tal:define="scale context/@@images"
    tal:replace="structure python:tag('image', scale='large', css_class='figure-img img-fluid')" />
```

The old way will not benefit from the `plone.scale` and [`plone.namedfile` improvements](https://github.com/plone/plone.namedfile/pull/113) for making a split between creating a tag and creating the actual scale.

A quick search shows templates in `plone.app.contenttypes` and `plone.app.event` that can be improved, but there may be more, as it is hard to search for this specific problem.

**Comment by jensens** [comment]
Is this solved with the above PR?

**Comment by mauritsvanrees** [comment]
No, in my original comment I noted a problem in `plone.app.event` and that is not solved yet.  And there are likely more templates that need fixing.  It is a bit hard to get a full list of problems without also getting false positives.  We may need to go through all templates that use `@@images` and check each use.

**Comment by jensens** [comment]
Still relevant for Plone 6. Templates should call @@images.tag() directly for plone.namedfile optimizations. Milestoned 6.1, assigned to mauritsvanrees.
