### ISSUE TITLE
Published object with effective date in the future is not shown in folder_contents view

### ISSUE THREAD

**Issue by 1letter** [plone/Products.CMFPlone#3571]
go to https://demo-latest-plone6.plone.org/

1. login as editor in chief
2. add a folder
3. publish the folder
4. add a page with effective date in the future
5. publish the page
6. go to the parent folder_contents view

the table is empty!

what i expect: the page that i added with a label "in the future"

**Comment by petschki** [comment]
long time ago, but this sounds like a regression: https://github.com/plone/Products.CMFPlone/pull/1952

**Comment by petschki** [comment]
If I'm the owner, I also expect that the page is visible regardless of the workflow state.

**Comment by petschki** [comment]
After some more investigations: not a regression but "hard to implement" ... as @davisagli already mentioned here https://community.plone.org/t/published-object-with-effective-date-in-the-future-is-not-shown-in-folder-contents-view/15410/2, the portal and a given path keyword in the query is checked for `AccessInactivePortalContent` ...

But I really would like to pull in more ideas to get this done (maybe) ...

I could think of an enhancement of the `AllowedRolesAndUsers` index to respect the `Access inactive portal content` permission too, instead of setting the `effectiveRange` ... but that's just a quick thought ... 

@thet as you've implemented the check in the `CatalogTool` maybe you have some more thoughts on this?

/cc @jensens @pbauer

**Comment by 1letter** [comment]
referring to the old discussions, i look in the code. it's hard to find a solution without wake up the full objects in the search result. i think it needs 3 parts to correctness:
1. for the folder_contents View a query paramter show_inactive=True is needed
2. the permissions of the state "private" in simple_publication_workflow should be changed, private mean "Owner" & "Manager" can view, access or edit - no others
3. a published item with an effective date in the future is published... other editors can view this item. for me is the "effective date in future" no security related, it's only a display feature for anonymous or members. all other roles can view this item.

**Comment by petschki** [comment]
`show_inactive=True` for folder_contents sounds like a good idea.

**Comment by yurj** [comment]
If the problem is only on the foldercontent view, I would fix it there instead of the catalog filtering. In a normal view (folderlisting/contentlisting) it is ok to not show the object even if I'm the owner, because it is inactive/expired (*). If the pat-structure can query the catalog in an unrestricted mode, that could be the solution? anyway, it depends on the context, so an adapter that adapt on the foldercontent view (and reuse most of the logic) could be the way?

(*) is inactive only when expired or there are other cases?

**Comment by petschki** [comment]
> (*) is inactive only when expired or there are other cases?

the check for `AccessInactivePortalContent` simply sets the `effectiveRange` index to today if not allowed ... so the range between effective_date and expiration_date is filtered.
My first idea with the `AllowedRolesAndUsers` index cannot work as this is set on creation/modification but the effectiveRange depends on the current datetime of course.

Solving this in `folder_contents` would be ok for me as @yurj suggests ... but I would set a `show_inactive` parameter in the `data-pat-structure` configuration and pass it to the `@@getVocabulary` view.

**Comment by 1letter** [comment]
@petschki where can i set this option? it's a rebuild of the js bundle needed? or exist an adapter like for tinymce to modify the pattern settings?

**Comment by petschki** [comment]
I think these 3 parts are needed:

- [ ] `pat-structure` needs the parameter in its defaults (=mockup rebuild)
- [ ] `plone.app.content.browser.contents` has to set the parameter in `FolderContentsView.get_options`
- [ ] `plone.app.content.browser.vocbulary` should pass the parameter to `plone.app.vocabularies.catalog` correctly

**Comment by 1letter** [comment]
The behavior is fixed on https://classic.demo.plone.org it is not reproducible, can this closed?

**Comment by davisagli** [comment]
Note: it's still an issue in Volto, but there is a fix here: https://github.com/plone/volto/pull/4764

**Comment by MrTango** [comment]
@1letter i still see the same issue in classic ui in Plone 6.12

**Comment by 1letter** [comment]
@MrTango okay, you're partly right. as editor in chief, all is fine. but as normal editor the issue exists

**Comment by yurj** [comment]
I've solved in a site assigning "Show inactive portal content" permission to the Editor role at portal level. Do you see any drawback? The question is: what was the use case when Editor should not see inactive portal content? We should document (@stevepiercy ) what the roles are supposed to mean before any code changing.

**Comment by stevepiercy** [comment]
Before I document anything, I need to know the roles, the object, and the permissions each role may perform on that object.

**Comment by yurj** [comment]
We need something like this https://5.docs.plone.org/working-with-content/collaboration-and-workflow/workflow-policies.html

Actually we've https://training.plone.org/workflow/roles-and-permissions.html which is pretty good IMHO.

Maybe we could add as an example the role "Content Manager" that has Contributor + Editor + Reviewer + Reader + has "view inactive content" permission that basically can go anywhere and change/publish/create content.

Then we've Site Admin which is a Content Manager but can also access the Site configurations. Finally, we've the Manager that can do everything.

**Comment by stevepiercy** [comment]
I'm fine with whatever y'all think is best.

We need to determine the audience. It sounds like a User Guide item, and not a Developer Guide item. Right now the Classic UI User Guide does not exist for Plone 6, but I hope that will change soon, once we can find a way to automate screenshots and videos. We also have an open PR to create a Developer Guide.

**Comment by yurj** [comment]
let not forget we've also this "byline" with a different logic:
https://github.com/plone/plone.app.contenttypes/blob/e37ec9a297ac8177c5b248171fc9636b16c7a200/plone/app/contenttypes/browser/templates/listing.pt#L91
(checks only views_about and doesn't display creation date)

**Comment by davisagli** [comment]
Granting the "Show inactive portal content" permission to the Editor role at the portal level is probably fine and should help with this in cases where the Editor role is granted to users or groups for the entire site. For users who only have the Editor role in a subsite or folder, the permission won't be there when the catalog is queried in the context of the entire site.

**Comment by jensens** [comment]
Verified still present. CatalogSource in plone/app/vocabularies/catalog.py calls catalog(query) without show_inactive=True. Effective date filtering hides future-effective items from folder_contents for non-manager editors.

**Comment by jensens** [comment]
**Analysis of the root cause:**

The folder_contents listing query goes through the vocabulary view (`plone.app.content/browser/vocabulary.py`) → `CatalogVocabularyFactory` → `catalog.searchResults()`. None of these pass `show_inactive=True`, so `CatalogTool.searchResults()` adds an `effectiveRange` filter that hides future-effective items.

Ironically, folder_contents *already* uses `show_inactive=True` for delete, rename, rearrange, and workflow actions (see `contents/__init__.py:87`, `delete.py:56`, `rename.py:64`, `rearrange.py:79`, `workflow.py:54`). Only the main listing query is missing it.

The simplest fix point would be `CatalogSource.search_catalog()` in `plone/app/vocabularies/catalog.py:866` — adding `show_inactive=True` to the query when the user has `AccessInactivePortalContent` permission on the current context. However, this vocabulary is also used outside folder_contents, so a blanket `show_inactive=True` could have unintended side effects.

An alternative would be to pass `show_inactive` through from the vocabulary view in `plone.app.content` when the request comes from folder_contents context.

This needs some thought on the right approach — it touches security-sensitive catalog filtering across multiple packages.
