### ISSUE TITLE
UnicodeEncodeError in CMFEditions for Plone 4.3.5 and 4.3.6

### ISSUE THREAD

**Issue by sneridagh** [plone/Products.CMFPlone#820]
It seems that a regresion was introduced from 4.3.5 in Products.CMFEditions for Plone 4.3.4 works fine.

Plone 4.3.4: Products.CMFEditions = 2.2.11
Plone 4.3.5: Products.CMFEditions = 2.2.13
Plone 4.3.6: Products.CMFEditions = 2.2.13
This is the traceback of the error.

```
We’re sorry, but there seems to be an error…

Here is the full error message:

Display traceback as text

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.CMFEditions.browser.diff, line 65, in __call__
    Module Products.Five.browser.pagetemplatefile, line 125, in __call__
    Module Products.Five.browser.pagetemplatefile, line 59, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module zope.pagetemplate.pagetemplate, line 240, in __call__
    Module zope.tal.talinterpreter, line 271, in __call__
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 858, in do_defineMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 946, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 852, in do_condition
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 852, in do_condition
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 821, in do_loop_tal
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
    Module zope.tales.tales, line 696, in evaluate
    URL: /home/timo/.buildout/eggs/Products.CMFEditions-2.2.13-py2.7.egg/Products/CMFEditions/browser/diff.pt
    Line 124, Column 16
    Expression: <PathExpr standard:u'diff/ndiff |\xa0nothing'>
    Names:

    {'args': (),
     'container': <Document at /Plone/front-page>,
     'context': <Document at /Plone/front-page>,
     'default': <object object at 0x7fd81aa094e0>,
     'here': <Document at /Plone/front-page>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7fd7ffb3dc00>,
     'request': <HTTPRequest, URL=http://localhost:8080/Plone/front-page/@@history>,
     'root': <Application at >,
     'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7fd804963d50>,
     'traverse_subpath': [],
     'user': <PropertiedUser 'admin'>,
     'view': <Products.Five.metaclass.DiffView object at 0x7fd7ffbffa10>,
     'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7fd804963ed0>}

    Module zope.tales.expressions, line 217, in __call__
    Module Products.PageTemplates.Expressions, line 155, in _eval
    Module Products.PageTemplates.Expressions, line 117, in render
    Module Products.CMFDiffTool.FieldDiff, line 52, in ndiff
    Module Products.CMFDiffTool.FieldDiff, line 63, in dump

UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 23: ordinal not in range(128)
```

**Comment by mauritsvanrees** [comment]
That character is actually in the template! Strange. Introduced in https://github.com/plone/Products.CMFEditions/commit/1e415bc4a67b1560e5426325a1a7516ce5ae1cda
I do not get the error locally, which is also strange.
Anway, I'll fix it in CMFEditions.

**Comment by mauritsvanrees** [comment]
Fixed in https://github.com/plone/Products.CMFEditions/commit/faa76e526727932f350d27c660ee13df2f0f6ec0

But @sneridagh can you check whether removing that unicode space from the template actually fixes it for you? It should definitely not be there, but I wonder if your error is caused by a different error which is really in that last line of the traceback, `Products.CMFDiffTool.FieldDiff, line 63, in dump`. At least I find it strange that the template has `\xa0` (a space or some other blank character) and the UnicodeEncodeError says `\xfc` (which is u-umlaut, ü) so that might be something in your content.
Should still work of course, but might be les easy to fix.

**Comment by mauritsvanrees** [comment]
For the record, in a Plone 4.3.6 site, without the fix linked above, when I edit a text and change 'support' into 'süpport', the diff shows just fine, without error.

**Comment by sneridagh** [comment]
I still have the issue with the fix while comparing two versions:
http://localhost:8080/Plone/asdasd/@@history?one=1&two=0
:(

I will try to debug it a bit this morning.

**Comment by sneridagh** [comment]
@mauritsvanrees I think I've found it. Sorry but I've forgot to mention that I've p.a.contenttypes installed too.

The template has been rearranged:
https://github.com/plone/Products.CMFEditions/blob/master/Products/CMFEditions/browser/diff.pt#L127

and now it always call to the `ndiff` method that in this line:
https://github.com/plone/Products.CMFDiffTool/blob/master/Products/CMFDiffTool/FieldDiff.py#L45

calls `_parseField` returns str for ATs and unicode for DXs.

then, when it calls the dump function in:
https://github.com/plone/Products.CMFDiffTool/blob/master/Products/CMFDiffTool/FieldDiff.py#L65

This casts str() to the unicode string that causes the UnicodeDecodeError (if the diff contains special characters).

I do not know how to proceed with it... should we change CMFDiffTool `dump` function to make it aware of unicode args before the cast?

**Comment by mauritsvanrees** [comment]
@sneridagh I am trying to fix it in CMFDiffTool. It has seen some unicode related fixes recently, but not this one yet.

And I guess it now goes wrong in CMFEditions because since its recent changes the ndiff is always computed, even when it is not necessary because there is already an html_diff that we would show.

**Comment by mauritsvanrees** [comment]
This fixes it: https://github.com/plone/Products.CMFDiffTool/commit/87a29172dd04090f360ff9ea37ea64fc14bb0ca9

**Comment by mauritsvanrees** [comment]
And for CMFEditions for good measure: https://github.com/plone/Products.CMFEditions/commit/3fcb68efe5c23850e9828952dd5751c7325d203d

**Comment by sneridagh** [comment]
@mauritsvanrees great! Thanks!
