### ISSUE TITLE
Linkintegrity test fails randomly on jenkins.plone.org

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#854]
http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/2255/robot/report/robot_log.html#s1-s15-t3

cc @pbauer

**Comment by pbauer** [comment]
@tisto I'll fix it

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/Products.CMFPlone/commit/1b50bd38bd668aaf5c02b0cdf806d746dd579a4d

**Comment by tisto** [comment]
@pbauer seems the test is still unstable: http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/2275/robot/report/robot_log.html#s1-s15-t3

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/Products.CMFPlone/commit/6d466dbcaee2e87828d0467ac5cebe689028d7d4

**Comment by tisto** [comment]
Test still fails randomly:

http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/2301/robot/report/robot_report.html#suites?s1-s15

**Comment by pbauer** [comment]
@tisto I have no clue how that can fail. After ``Wait Until Page Contains Element  css=.pattern-relateditems-result-select.selectable`` there should not be a problem clicking the same element with ``Click Link  css=.pattern-relateditems-result-select.selectable``. Ideas?

**Comment by tisto** [comment]
@pbauer the element could not be visible (then you need to use "wait until element is visible", sometimes other html elements have a higher z-index so the underlying element can not be clicked. "Wait until page contains" just makes sure the element is there, not that the page is fully loaded and the javascript code has been fully executed. It is also quite common that the underlying JS implementation itself is fragile. Selenium can't fix that then...

**Comment by pbauer** [comment]
@tisto thanks for the tip

**Comment by pbauer** [comment]
I think I finally fixed the test for good in https://github.com/plone/Products.CMFPlone/commit/e409071730f74df3b404625783d8e61f8c70551a

The main problem was that ``css=.pattern-relateditems-result-select.selectable`` (linkable items) existed multiple times before entering `Foo` and only once afterwards. So the ``Wait until element is visible`` caught one from the initial list that disappeared before clicking due to the entred text. Now I wait until the result is exactly what I need using ``Wait until element is visible  jquery=.select2-highlighted .pattern-relateditems-result-select.selectable:contains(Foo)``. 
By the way: the jquery-selector is awesome. Much easier to write that xpath or css.

**Comment by mauritsvanrees** [comment]
Awesome! Thanks a lot.
