### ISSUE TITLE
Missing personal toolbar when expanding the horizontal toolbar

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#950]
The toolbar with icons only:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9817765/37e2c0ce-587b-11e5-83e1-eb1df88cf52f.png)

The toolbar expanded with legends; the user icon is missing:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9817763/37830576-587b-11e5-8ac1-bfb67ddecec6.png)

**Comment by vangheem** [comment]
\cc @bloodbare

**Comment by ichim-david** [comment]
It's not missing, it's just moved to the bottom below the toolbar.
At least with plone 5.0rc I can still see faintly the white text.
I am checking the css to see if I can easily fix it.

On a side note what a frustrating way to find out how to change the toolbar from left to top. 
I tried to search google how to change the pattern and the best that I got was code talk such as this
https://github.com/plone/plone.app.layout/commit/176bdcaa042dc79ec67f84ac75ca7936a1b1ef2b
where I had to go in configuration resources and change the option from the side to the top as modifying the class to use in viewlets/toolbar.pt didn't make any difference ( turns out the classes need to be added on the body).

**Comment by hvelarde** [comment]
@ichim-david there's an option on the Site control panel configlet for that.

**Comment by pbauer** [comment]
@ichim-david that is http://localhost:8080/Plone/@@site-controlpanel

**Comment by ichim-david** [comment]
I have started working on this issue within a branch as can be seen within the referenced commit.
Basically in order for the personal toolbar to always remain visible and on the toolbar we need
to move also content views which I chose to move from right to left as can be seen from the following screenshot:
![more-menu](https://cloud.githubusercontent.com/assets/152852/9839084/2586416e-5a77-11e5-989a-e7fe39130045.png)
 
I still have some small cleaning up to do and to add some comments to the changed code but it is already a lot cleaner that it was before.

I am still surprised though that 1280px can't fully display the toolbar using the German translation and
I think we should fix this even if we need to lower some of the padding and/or font size.

**Comment by ichim-david** [comment]
Found more issues when the more options is clicked and you contract the toolbar, the more-options move back to the toolbar however they don't have enough room to display the text and the popup is displaced.
See screenshot:
![after-fix](https://cloud.githubusercontent.com/assets/152852/9842918/69d76910-5abd-11e5-9e05-ed17cb9e2589.png)

Still better that what was before but the whole more button selected action I will need to check.
For starters if I contract or expand I think the more options should be hidden.

**Comment by hvelarde** [comment]
@ichim-david thanks, for taking car of this; the is something else that seems weird to me: why the name of the menu item appears duplicated on all menus?

![selection_004](https://cloud.githubusercontent.com/assets/341393/9850982/c5656250-5acc-11e5-924c-7cd3dde14851.png)

![selection_005](https://cloud.githubusercontent.com/assets/341393/9851006/f0783f26-5acc-11e5-88e2-4978c8a6f0a2.png)

**Comment by bloodbare** [comment]
Hey, 

We implemented some solution to fit the toolbar on horizontal in a rush some weeks ago: the more button. Its not perfect, neither is nice, but we saw that its impossible to make it feet in 1200px the menu with texts. 

The code is there : 
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/static/patterns/toolbar/src/toolbar.js#L219

The problem was that the calculation were not acurate and there where a bunch of container size where it was misscalculated.

Its great somebody is taking care of it!

**Comment by ichim-david** [comment]
@hvelarde this is the way it was coded, if you look at plone.app.contentmenu 
or plone.app.layout and search for plone-toolbar-submenu-header you will find it present as a submenu.

I think it might be too late to get rid of them as a design decision now but you could easily hide them with this css line
    .plone-toolbar-submenu-header:first-child { display: none;}
it is normally found in toolbar.plone.less from CMFPlone.

If others agree with your assessment they can easily be removed.

**Comment by davilima6** [comment]
I agree menu titles shouldn't be repeated. That was useful when Options submenu brought both Portlet management and Display menu links. But that should be another issue.

**Comment by hvelarde** [comment]
I will open a new issue for that then.

**Comment by ichim-david** [comment]
I've added a pull request fixing this issue and a couple of other issues as well.
I wanted to add a jenkins build but it seems I don't have permissions.

**Comment by hvelarde** [comment]
I already added it.

**Comment by ichim-david** [comment]
Fixes committed to CMFPlone from pull request https://github.com/plone/Products.CMFPlone/pull/1009
A new commit will need to be done to compile plone resources otherwise you will get the fixes only
when in devel mode.
I can't do this now since I've upgraded to node 4.0 and plone-compile-resources script fails with it.
@hvelarde  maybe you can update the plone compiled resources.

**Comment by hvelarde** [comment]
This is still happening in Plone 5.0 final; I'm going to open another issue describing it with more details.
